batasibuk/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as home_views
from account.views import AccountCreate,ProfileView,CreatorView
from account.forms import AccountLoginForm
from account import views as account_views
from batasibuk_forum.views import ChannelView,ThreadView
from batasibuk_forum import views as forum_views
from chat.views import ChatRoomView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
	path('chat/',ChatRoomView.as_view(),name='chat'),
	path('search/',home_views.SearchView.as_view(),name='search'),
	path('',home_views.Index.as_view(),name='home'),
	path('thread/<slug:slug_thread>/<str:name_thread>/',ThreadView.as_view(),name='thread'),
	path('ajax/thread/<slug:slug_thread>/<str:name_thread>/',ThreadView.as_view(mode='ajax'),name='ajaxthread'),
	path('channel/<int:id_channel>/<str:name_channel>/',ChannelView.as_view(),name='channel'),
	path('forum/',include('batasibuk_forum.urls',namespace='forum')),
	path('register/',AccountCreate.as_view(),name='register'),
	path('login',auth_views.LoginView.as_view(template_name='account/login.html',authentication_form=AccountLoginForm),name='login'),
	path('profile/<user_username>',ProfileView.as_view(),name='profile'),
	path('creator/<user_username>',CreatorView.as_view(),name='creator'),
	path('logout',auth_views.LogoutView.as_view(),name='logout'),
	path('api/posts/<post_slug>/delete',forum_views.delete_thread,name='delete'),
	path('api/posts/<post_id>/vote_r',forum_views.vote_r,name='vote_r'),
	path('api/posts/<post_slug>/upvote',forum_views.upvote_post,name='upvote_post'),
	path('api/posts/<post_slug>/downvote',forum_views.downvote_post,name='downvote_post'),
	path('api/comments/<comment_id>/upvote',forum_views.upvote_comment,name='upvote_comment'),
	path('api/comments/<comment_id>/downvote',forum_views.downvote_comment,name='downvote_comment'),
	path('api/follow/<user_id>/user',account_views.account_follow,name='follow_user'),
	path('api/follow/<forum_id>/<forum_type>',forum_views.forum_follow,name='follow_forum'),
	path('api/get_replys/<comment_id>',forum_views.get_replys,name='get_replys'),
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

batasibuk_forum/urls.py
from django.urls import path
from .views import (NewPostView,
				   HomeForumsView,
				   ForumView,
				   ThreadView,
				   )

app_name='batasibuk_forum'

urlpatterns=[
	path('',HomeForumsView.as_view(),name='home'),
	path('fr-<int:id_forum>/<str:name_forum>/',ForumView.as_view(mode='forum'),name='forumview'),
	path('sfr-<int:id_forum>/<str:name_forum>/',ForumView.as_view(mode='subforum'),name='subforumview'),
	path('newthread/',NewPostView.as_view(),name='newthread'),
	path('update/<slug:slug_thread>/thread',NewPostView.as_view(mode='update'),name='updatethread'),
]

batasibuk_forum/forms.py
from django import forms
from .fields import ListTextWidget
from .models import (Forum,SubForum,Post,Comment)

class NewPostForm(forms.ModelForm):
	select_forum=forms.ChoiceField(required=True,choices=[])
	class Meta:
		model=Post
		fields=['select_forum','post_title','body']
	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		choices=[]
		for forum in Forum.objects.all():
			choices.append((f'fr-{forum.id}',forum.name))
			if forum.subforums.all():
				for subforum in forum.subforums.all():
					choices.append((f'sfr-{subforum.id}',subforum.name))
		self.fields['select_forum'].choices=choices
		self.fields['post_title'].widget.attrs={'class':'form-control','placeholder':'Masukan Judul','data-emojiable':"true",'style':'position:relative'}
		self.fields['post_title'].label="Judul"
		self.fields['body'].label="Detail"
		self.fields['body'].widget.attrs={'class':'form-control','style':'width:100%;'}
		self.fields['select_forum'].label='Forum'
		self.fields['select_forum'].widget.attrs={'class':'selectpicker','data-live-search':'true'}


class NewCommentForm(forms.ModelForm):
	id_parent_comment=forms.IntegerField(widget=forms.HiddenInput(),required=False)
	class Meta:
		model=Comment
		fields=['body','id_parent_comment']
	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		self.fields['body'].widget.attrs={'class':'form-control','placeholder':'Berikan Komentar untuk Thread ini'}

batasibuk_forum/views.py
from copy import deepcopy
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse,JsonResponse,HttpResponseNotFound
from django.views.generic import View,CreateView, ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormMixin
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from .forms import NewPostForm,NewCommentForm
from .models import (Category,
					SubForum,
					Forum,
					Post,ViewPost,Comment)
# Create your views here.



UPVOTE=1
DOWNVOTE=2

class HomeForumsView(ListView):
	model= Category
	template_name='batasibuk_forum/home.html'
	context_object_name='categorys'
	extra_context={
		'title':'forum'
	}

class ChannelView(ListView):
	model=Forum
	template_name='batasibuk_forum/channel_view.html'
	context_object_name='channel_forums'
	def get_context_data(self,*args,**kwargs):
		context=super().get_context_data(*args,**kwargs)
		context['title']=self.kwargs['name_channel']
		return context
	def get_queryset(self):
		query=super().get_queryset()
		category=Category.objects.get(id=self.kwargs['id_channel'])
		return query.filter(category=category)


class ForumView(ListView):
	model=Post
	mode=None
	paginate_by=5
	template_name='batasibuk_forum/forum_view.html'
	context_object_name='forum_thread'
	def get_context_data(self,*args,**kwargs):
		context=super().get_context_data(*args,**kwargs)
		context['title']=self.kwargs['name_forum']
		context['detail_forum']=(self.mode,self.kwargs['id_forum'])
		context['this_forum']=Forum.objects.filter(pk=self.kwargs['id_forum']).first()
		if self.mode=='subforum':
			context['this_forum']=SubForum.objects.filter(pk=self.kwargs['id_forum']).first()
		return context
	def get_queryset(self):
		query=super().get_queryset()
		forum_type=ContentType.objects.get_for_model(Forum)
		if self.mode=='subforum':
			forum_type=ContentType.objects.get_for_model(SubForum)
		return query.filter(forum_post_type=forum_type,forum_post_id=self.kwargs['id_forum'],status=1).order_by('-created')


class NewPostView(LoginRequiredMixin,UserPassesTestMixin,View):
	template_name='batasibuk_forum/new_thread.html'
	form_class=NewPostForm()
	mode=None
	context={}
	def get(self,*args,**kwargs):
		if self.mode=='update':
			data_thread=self.thread_update.__dict__
			self.form_class=NewPostForm(initial=data_thread,instance=self.thread_update)
		self.context={
			'title':'New Thread',
			'form':self.form_class
		}
		if kwargs.get('slug_thread',False):
			self.context['title']=f"Update : {self.thread_update.post_title}"
		return render(self.request,self.template_name,self.context)
	def post(self,*args,**kwargs):
		self.form_class=NewPostForm(self.request.POST)
		if kwargs.get('slug_thread',False):
			self.form_class=NewPostForm(self.request.POST,instance=self.thread_update)
		if self.form_class.is_valid():
			thread_post=self.form_class.save(commit=False)
			thread_post.author=self.request.user
			jenis,id_jenis=self.form_class.cleaned_data.get('select_forum').split('-')
			if jenis=='fr':
				f=Forum.objects.get(id=id_jenis)
			elif jenis=='sfr':
				f=SubForum.objects.get(id=id_jenis)
			thread_post.content_forum_post=deepcopy(f)
			if 'post' in self.request.POST:
				thread_post.status=1
			thread_post.save()
		return redirect(reverse('thread',args=(thread_post.post_slug,thread_post.post_title)))
	def test_func(self):
		if self.mode=='update':
			self.thread_update=Post.objects.filter(post_slug=self.kwargs['slug_thread']).first()
			if self.request.user==self.thread_update.author:
				return True
			else:
				return False
		else:
			return True
def record_view(request,slug_thread):
	post=get_object_or_404(Post,post_slug=slug_thread)
	if request.user.is_authenticated:
		if not ViewPost.objects.filter(post=post,session=request.session.session_key,user=request.user).exists():
			view=ViewPost(post=post,ip=request.META['REMOTE_ADDR'],session=request.session.session_key,user=request.user)
			view.save()
	return ViewPost.objects.filter(post=post).count()

class ThreadView(FormMixin,DetailView):
	model=Post
	mode=None
	template_name='batasibuk_forum/thread_view.html'
	context_object_name='thread'
	slug_url_kwarg='slug_thread'
	slug_field='post_slug'
	form_class=NewCommentForm

	def get_success_url(self):
		return reverse('thread',kwargs={'slug_thread':self.kwargs['slug_thread'],'name_thread':self.kwargs['name_thread']})
	def get_context_data(self,*args,**kwargs):
		context=super().get_context_data(*args,**kwargs)
		context['title']=self.kwargs['name_thread']
		context['forms_comment']=NewCommentForm()
		context['comments']=self.object.post_comments.filter(comment_parent=None)
		return context
	def get_queryset(self):
		query=super().get_queryset()
		post=self.model.objects.get(post_slug=self.kwargs['slug_thread'])
		post.views=int(record_view(self.request,self.kwargs['slug_thread']))
		post.save()
		return query.filter(post_slug=self.kwargs['slug_thread'],status=1)

	def post(self,request,*args,**kwargs):
		if self.request.user.is_authenticated:
			form=self.get_form()
			if form.is_valid():
				return self.form_valid(form) 
			else:
				return self.form_invalid(form)
		return redirect(reverse('login')+"?next="+self.request.build_absolute_uri())

	def form_valid(self,form):
		post=self.get_object()
		user=self.request.user
		new_comment=form.save(commit=False)
		new_comment.post=post
		new_comment.user=user
		id_parent_comment=form.cleaned_data['id_parent_comment']
		if id_parent_comment:
			parent=Comment.objects.filter(pk=id_parent_comment).first()
			new_comment.comment_parent=parent

		new_comment.save()
		if self.mode=='ajax':
			if id_parent_comment:
				data_comment={
					'reply':[new_comment]
				}
				data_comment=render(self.request,'batasibuk_forum/reply.html',data_comment)
			else:
				data_comment={
					'all_comment':[new_comment]
				}
				data_comment=render(self.request,'batasibuk_forum/comments.html',data_comment)

			return HttpResponse(data_comment)
		return super().form_valid(form)

def delete_thread(request,post_slug):
	if request.user.is_authenticated:
		thread=get_object_or_404(Post,post_slug=post_slug)
		if request.user==thread.author:
			thread.delete()
			data={
				'delete':1,
				'count-posts':thread.author.posts.all().count()
			}
		else:
			data={
				'delete':0
			}
			raise PermissionDenied()
	else:
		return redirect_login(reverse('login'))

	return JsonResponse(data)

def upvote_post(request,post_slug):
	if request.user.is_authenticated:
		post=get_object_or_404(Post,post_slug=post_slug)
		post.upvote(request.user)
		data={
			'redirect_login':0,
			'upvotes':str(post.upvotes),
			'downvotes':str(post.downvotes),
		}
		if post.vote_self:
			return HttpResponseNotFound()
	else:
		data={
			'redirect_login':1
		}

	if request.is_ajax():
		return JsonResponse(data)
	else:
		return redirect(reverse('thread',args=(post.post_slug,post.post_title)))


def downvote_post(request,post_slug):
	if request.user.is_authenticated:
		post=get_object_or_404(Post,post_slug=post_slug)
		post.downvote(request.user)
		data={
			'redirect_login':0,
			'upvotes':str(post.upvotes),
			'downvotes':str(post.downvotes),
		}
		if post.vote_self:
			return HttpResponseNotFound()
	else:
		data={
			'redirect_login':1
		}

	if request.is_ajax():
		return JsonResponse(data)
	else:
		return redirect(reverse('thread',args=(post.post_slug,post.post_title)))

def upvote_comment(request,comment_id):
	if request.user.is_authenticated:
		comment=get_object_or_404(Comment,pk=comment_id)
		comment.upvote(request.user)
		data={
			'redirect_login':0,
			'upvotes':str(comment.upvotes),
			'downvotes':str(comment.downvotes),
		}
		if comment.vote_self:
			return HttpResponseNotFound()
	else:
		data={
			'redirect_login':1,
		}
	if request.is_ajax():
		return JsonResponse(data)
	else:
		post=comment.post
		return redirect(reverse('thread',args=(post.post_slug,post.post_title)))


def downvote_comment(request,comment_id):
	if request.user.is_authenticated:
		comment=get_object_or_404(Comment,pk=comment_id)
		comment.downvote(request.user)
		data={
			'redirect_login':0,
			'upvotes':str(comment.upvotes),
			'downvotes':str(comment.downvotes)
		}
		if comment.vote_self:
			return HttpResponseNotFound()
	else:
		data={
			'redirect_login':1,
		}
	if request.is_ajax():
		return JsonResponse(data)
	else:
		post=comment.post
		return redirect(reverse('thread',args=(post.post_slug,post.post_title)))

def forum_follow(request,forum_id,forum_type):
	if request.user.is_authenticated:
		if forum_type=='forum':
			forum=get_object_or_404(Forum,pk=forum_id)
		elif forum_type=='subforum':
			forum=get_object_or_404(SubForum,pk=forum_id)
		else:
			return HttpResponseNotFound()

		forum._follow(request.user)
		data={
			'redirect_login':0,
			'sum_follow':forum.sum_follow,
			'follow_state_action':forum.follow_state_action
		}
	else:
		data={
			'redirect_login':1
		}

	if request.is_ajax():
		return JsonResponse(data)
	else:
		return redirect(request.GET.get('next'))

def vote_r(request,post_id):
	if request.user.is_authenticated:
		post=get_object_or_404(Post,pk=post_id)
		action,score=post._vote_r(request.user)
		data={
			'redirect_login':0,
			'action':action,
			'score':score,
		}
	else:
		data={
			'redirect_login':1,
		}
	if request.is_ajax():
		return JsonResponse(data)
	else:
		return redirect(reverse('thread',kwargs={'slug_thread':post.post_slug,'name_thread':post.post_title}))

def get_replys(request,comment_id):
	comment=get_object_or_404(Comment,pk=comment_id)
	reply=comment.comment_reply.all()
	data={
		'reply':reply
	}	
	data=render(request,'batasibuk_forum/reply.html',data)


	return HttpResponse(data)

batasibuk_forum/templates/batasibuk_forum/channel_view.html
{% extends "base.html" %}
{% load static %}
{% load top_recommend %}

{% block get_in_head %}
	<link rel="stylesheet" type="text/css" href="{% static "css/channel_view.css" %}">
{% endblock get_in_head %}



{% block main_content %}

<div class="row">
	<!-- side left-->
	<div class="col-md-3 d-none d-md-block order-md-1">
		{% if user.is_authenticated %}
			{% include "snippets/profile_card.html" %}
		{% endif %}
      	
        <!-- top recommend-->
    	{%top_recommend%}
    	<!-- end top recommend-->
    </div>
    <!-- end side left-->


    <!-- Main Content-->
    <div class="col-md-6 order-1 order-md-2 ">
    		{% if user.is_authenticated %}
    			<!-- Post Create-->
	            {% include "snippets/post_create.html" %}
	            <!-- Post CreateEnd-->
    		{% endif %}
            

            <div class="wrap-channel container-fluid shadow">
            	<h4>Channel {{title}}</h4>
	            <div class="row p-2">
	            	{% with channel_forums as forums  %}
	            	    {% include "snippets/container_card_forum.html" %}
	            	{% endwith %}
	            </div>	
            </div>
   
    </div>
    <!-- Main Content-->

    <!-- Side right-->
    <div class="col-md-3 order-2 order-md-3">
    	
	     <!--forum recommend-->
      		{%forum_recommend request%}
       	<!--end forum recommend-->
	   	{% include "snippets/footer.html" %}
	 </div>
	 <!-- end side right-->
</div>

{% endblock main_content %}

{% block costum_js %}
    {% include "snippets/follow.html" %}
{% endblock costum_js %}

batasibuk_forum/templates/batasibuk_forum/comments.html
{% load vote_follow_filter %}
{% for c in all_comment  %}
<div class="detail-comment mb-3">
	<div class="post-comment parent-comment d-flex flex-row align-items-start">
       <img src="{{c.user.profile.user_photo.url}}" class="img-fluid user-photo">
       <p>
		<span>{{c.user}}</span>
		 {{c.body|safe}}
		</p>
    </div>
	<div class="reaction mb-2 ml-5">
		<a href="javascript:void(0)" class="btn btn-claps btn-claps-sm vote-this {{c|is_user_upvote:request}}" data-id="{{c.id}}" data-cat='comments' data-action='up'>
		{% include "snippets/claps-sm.svg" %}
		</a><span id="up-{{c.id}}">{{c.upvotes}}</span>
		
		<a href='javascript:void(0)' class="btn btn-punch btn-punch-sm vote-this {{c|is_user_downvote:request}}" data-id="{{c.id}}" data-cat='comments' data-action='down'>
			{% include "snippets/punch-sm.svg" %}
		</a>
		<span id="down-{{c.id}}">{{c.downvotes}}</span>
		<a href='javascript:void(0)' data-reply-show="data-reply-{{c.pk}}" data-id="{{c.pk}}" class="show-data-reply"><span class="d-inline-block">&nbsp;<i class="fa fa-comments-o fa-lg"></i> <span id="count-reply-{{c.pk}}">{{c.comment_reply.all.count}}</span> Balasan</span></a>
		<a href='javascript:void(0)'data-form-show="form-reply-{{c.pk}}" class="show-form-reply">Balas</a>
		
	</div>
	<!-- daftar reply-->
		<div id="data-reply-{{c.pk}}" class="data-reply pl-5">

		</div>
		<!-- end daftar reply-->
		<!-- form reply-->
		<div id="form-reply-{{c.pk}}" class="d-none form-reply mt-2 pl-4">
		<form method="post" class="form-comment">
			{% csrf_token %}
			<input name="id_parent_comment" id="id_id_parent_comment" type="hidden" value={{c.pk}}>
			<p>
			<textarea name="body" class="form-control" placeholder="Berikan Komentar untuk Thread ini" id="id_body-{{c.pk}}"></textarea></p>
			<div class="text-right">
				<button type="submit" class="d-inline-block btn btn-orange mr-3" data-action='submit-form' data-type='reply'>Balas</button>
			</div>
			
		</form>
		</div>
		<!-- end form reply-->
		<div class="hr-custom mt-2"></div>
</div>
{%empty%}
<p id="none-comment">Tidak ada komentar</p>
{% endfor %}

batasibuk_forum/templates/batasibuk_forum/forum_view.html
{% extends "base.html" %}
{% load static %}
{% load vote_follow_filter %}
{% load top_recommend %}

{% block get_in_head %}
	{% include "snippets/highlight/highlight_css_js.html" %}
	<link rel="stylesheet" type="text/css" href="{% static "css/forum_view.css" %}">
{% endblock get_in_head %}


{% block main_content %}

<div class="row">
	<div class="col-md-3 d-none d-md-block order-md-1">
		{% if user.is_authenticated %}
			{% include "snippets/profile_card.html" %}
		{% endif %}
        <!-- top recommend-->
    	{%top_recommend%}
    	<!-- end top recommend-->
    </div>
    <div class="col-md-6 order-1 order-md-2 ">

    		{% if user.is_authenticated %}
	    		 <!-- Post Create-->
	            {% include "snippets/post_create.html" %}
	            <!-- Post CreateEnd-->
    		{% endif %}
           

            <div class="wrap-forum shadow">
            	<h4>{{title|capfirst}}</h4>
            	<a href="javascript:void(0)" class="btn btn-follow follow-this {%is_user_follow this_forum request%} " data-id='{{detail_forum.1}}' data-action='{{detail_forum.0}}'>{%is_user_follow this_forum request 'get_text'%}</a>

            	<div class="detail-forum mt-3">
            		<ul class="nav nav-tabs" id="tab-forum" role='tablist'>
            			<li class="nav-item">
            				<a class="nav-link active" href="#content-posts" id="posts-tab" data-toggle='tab' role='tab'  aria-selected='true' aria-controls='posts'>Posts</a>
            			</li>
            			{% if detail_forum.0 == 'forum' %}
            				<li class="nav-item">
            					<a class="nav-link" href="#content-subforums" id="subforums-tab" data-toggle='tab' role='tab' aria-controls='subforums'>
            						SubForums
            					</a>
            				</li>
            			{% endif %}
            		</ul>
            		<div class="tab-content" id="content-forum">
            			<div class="tab-pane fade show active" id='content-posts' role='tabpanel' arial-labelledby='posts-tab'>
            				{% with forum_thread as threads  %}
            				    {% include "snippets/container_card_threads.html" %}
            				{% endwith %}
							<!--if all threads has paginated-->
								{% include "snippets/this_paginated.html" %}
							<!--end if all threads has paginated-->
            			</div>
            			<!--if forum has subforum-->
       					{% if detail_forum.0 == 'forum' %}
       					<div class="tab-pane fade" id="content-subforums" role='tabpanel' arial-labelledby='subforums-tab'>
       						<div class="row p-3 ">
       							{% for subforum in this_forum.subforums.all %}
			                    		<div class="forum-detail col-sm-6">
			                    			<a href="{% url "forum:subforumview" id_forum=subforum.id name_forum=subforum.name %}" class="remove-link-format"> 
				                    		<div class="forum-info">
				                    			<img src="/media/logo_image/logocoba.jpg" class="img-fluid forum-logo">
				                    			<div class="forum-posts d-flex flex-column justify-content-center">
				                    				<p>{{subforum.posts.all.count}} Post{{subforum.posts.all.count|pluralize}}</p>
				                    			</div>
				                    		</div>
											<p>{{subforum.name|capfirst}}</p>
											</a>
										</div>
								{%empty%}
       							<p>Tidak Ada SubForum</p>	
								{% endfor %}
       						</div>
       					</div>
       					{% endif %}
       					<!--end if forum has subforum-->
            		</div>

            	</div>

            </div>
    </div>
    <div class="col-md-3 order-2 order-md-3">
    	
	     <!--forum recommend-->
      {%forum_recommend request%}
       <!--end forum recommend-->
	   	{% include "snippets/footer.html" %}
	 </div>
</div>

{% endblock main_content %}


{% block costum_js %}
	{% include "snippets/follow.html" %}
  {% include "snippets/delete_thread.html" %}
{% endblock costum_js %}

batasibuk_forum/templates/batasibuk_forum/home.html
{% extends "base.html" %}
{% load static %}
{% load top_recommend %}

{% block get_in_head %}

	<link rel="stylesheet" type="text/css" href="{% static "css/forum_home.css" %}">
	
{% endblock get_in_head %}



{% block main_content %}

<div class="row">
	<div class="col-md-3 d-none d-md-block order-md-1">
		{% if user.is_authenticated %}
			{% include "snippets/profile_card.html" %}
		{% endif %}
      	
        <!-- top recommend-->
    	{%top_recommend%}
    	<!-- end top recommend-->
    </div>
    <div class="col-md-6 order-1 order-md-2 ">
    		{% if user.is_authenticated %}
    			<!-- Post Create-->
            	{% include "snippets/post_create.html" %}
            	<!-- Post CreateEnd-->
    		{% endif %}
           

            <div class="chanels-card">
            {% for category in categorys  %}
				<div class="chanel-detail shadow">
                 	<img src="/media/logo_image/190331210525.png" alt="user" class="chanel-logo" />
                  <div class="channel-info">
                  	<a href="{% url "channel" id_channel=category.id name_channel=category.name%}" class="remove-link-format">
                    <h5 class="channel-title">Chanels {{category.name|capfirst}}</h5>
                    	<p>{{category.forums.all.count}} Forum{{category.forums.all.count|pluralize}}</p>
                    </a>
                  </div>
                  <div class="hr-custom clearfix"></div>
                  <div class="chanel-forum container-fluid">
                    	<h6>{{category.name|capfirst}} Forums </h6>
                    	<div class="row">
                    	{% for forum in category.forums.all %}
	                    		<div class="forum-detail col-sm-6">
	                    			<a href="{% url "forum:forumview" id_forum=forum.id name_forum=forum.name %}" class="remove-link-format"> 
		                    		<div class="forum-info">
		                    			<img src="/media/logo_image/logocoba.jpg" class="img-fluid forum-logo">
		                    			<div class="forum-posts d-flex flex-column justify-content-center">
		                    				<p>{{forum.posts.all.count}} Post{{forum.posts.all.count|pluralize}}</p>
		                    				<p>{{forum.subforums.all.count}} SubForum{{forum.subforum.all.count|pluralize}}</p>
		                    			</div>
		                    		</div>
									<p>{{forum.name|capfirst}}</p>
									</a>
								</div>
						{% endfor %}
						<div class="col-sm-6 d-flex align-items-center justify-content-center">
							<a href="{% url "channel" id_channel=category.id name_channel=category.name %}" class="link-all-forum">
								<p>
									<i class="fa fa-arrow-right"></i>
									See All Forum
								</p>
									
							</a>
						</div>
						
						</div>
						
                  </div>
                  
                </div>
			{% endfor %}
            </div>
   
    </div>
    <div class="col-md-3 order-2 order-md-3">
    	
	     <!--forum recommend-->
      {%forum_recommend request%}
       <!--end forum recommend-->
	   	{% include "snippets/footer.html" %}
	 </div>
</div>

{% endblock main_content %}
{% block costum_js %}
	{% include "snippets/follow.html" %}
{% endblock costum_js %}

batasibuk_forum/templates/batasibuk_forum/new_thread.html
{% extends "base.html" %}
{% load static %}

{% block get_in_head %}
	{{form.media}}
	{% include "snippets/emojipicker/emoji_css.html" %}
	
    <link rel="stylesheet" type="text/css" href="{% static "css/new_thread.css" %}">

{% endblock get_in_head %}

	
{% block main_content %}
<div class="row">
	<div class=" col-lg-9 mx-auto">
		<div class="wrap-create-post shadows">
			<h3>Buat Thread</h3>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% for f in form  %}

					<div class="form-group">
						<label for="{{f.id_for_label}}"><strong>{{f.label}}</strong></label>
						<p class="input-container">{{f}}</p>
					</div>
					
				{% endfor %}
				<div class="text-center">
					<button type="submit" name="draft" class=" ml-auto btn btn-outline-orange mr-3">
					Simpan Draft
					</button>
					<button type="submit" name="post"  class="btn btn-orange px-4">
					Publish
					</button>
				</div>
				
			</form>
			<div class="mx-auto img-logo">
				<img src="{% static "image/logo.png" %}">
			</div>
		</div>		
	</div>
</div>
{% endblock main_content %}

{% block costum_js %}
	{% include "snippets/emojipicker/emoji_js.html" %}
{% endblock costum_js %}

batasibuk_forum/templates/batasibuk_forum/reply.html
{% load vote_follow_filter %}


{% for c in reply  %}
						<div class="detail-comment">
							<div class="post-comment d-flex flex-row align-items-start">
				               <img src="{{c.user.profile.user_photo.url}}" class="img-fluid user-photo">
				               <p>
								<span>{{c.user}}</span>
								 {{c.body|safe}}
								</p>
				            </div>
							<div class="reaction ml-5">
								<a href="javascript:void(0)" class="btn btn-claps btn-claps-sm vote-this {{c|is_user_upvote:request}}" data-id="{{c.id}}" data-cat='comments' data-action='up'>
								{% include "snippets/claps-sm.svg" %}
								</a><span id="up-{{c.id}}">{{c.upvotes}}</span>
								
								<a href='javascript:void(0)' class="btn btn-punch btn-punch-sm vote-this {{c|is_user_downvote:request}}" data-id="{{c.id}}" data-cat='comments' data-action='down'>
									{% include "snippets/punch-sm.svg" %}
								</a><span id="down-{{c.id}}">{{c.downvotes}}</span>
								
								
							</div>

						
						</div>
						{%empty%}
						<p id="none-reply">Tidak Balasan</p>
					{% endfor %}