batasibuk/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as home_views
from account.views import AccountCreate,ProfileView,CreatorView
from account.forms import AccountLoginForm
from account import views as account_views
from batasibuk_forum.views import ChannelView,ThreadView
from batasibuk_forum import views as forum_views
from chat.views import ChatRoomView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
	path('chat/',ChatRoomView.as_view(),name='chat'),
	path('search/',home_views.SearchView.as_view(),name='search'),
	path('',home_views.Index.as_view(),name='home'),
	path('thread/<slug:slug_thread>/<str:name_thread>/',ThreadView.as_view(),name='thread'),
	path('ajax/thread/<slug:slug_thread>/<str:name_thread>/',ThreadView.as_view(mode='ajax'),name='ajaxthread'),
	path('channel/<int:id_channel>/<str:name_channel>/',ChannelView.as_view(),name='channel'),
	path('forum/',include('batasibuk_forum.urls',namespace='forum')),
	path('register/',AccountCreate.as_view(),name='register'),
	path('login',auth_views.LoginView.as_view(template_name='account/login.html',authentication_form=AccountLoginForm),name='login'),
	path('profile/<user_username>',ProfileView.as_view(),name='profile'),
	path('creator/<user_username>',CreatorView.as_view(),name='creator'),
	path('logout',auth_views.LogoutView.as_view(),name='logout'),
	path('api/posts/<post_slug>/delete',forum_views.delete_thread,name='delete'),
	path('api/posts/<post_id>/vote_r',forum_views.vote_r,name='vote_r'),
	path('api/posts/<post_slug>/upvote',forum_views.upvote_post,name='upvote_post'),
	path('api/posts/<post_slug>/downvote',forum_views.downvote_post,name='downvote_post'),
	path('api/comments/<comment_id>/upvote',forum_views.upvote_comment,name='upvote_comment'),
	path('api/comments/<comment_id>/downvote',forum_views.downvote_comment,name='downvote_comment'),
	path('api/follow/<user_id>/user',account_views.account_follow,name='follow_user'),
	path('api/follow/<forum_id>/<forum_type>',forum_views.forum_follow,name='follow_forum'),
	path('api/get_replys/<comment_id>',forum_views.get_replys,name='get_replys'),
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

batasibuk_forum/urls.py
from django.urls import path
from .views import (NewPostView,
				   HomeForumsView,
				   ForumView,
				   ThreadView,
				   )

app_name='batasibuk_forum'

urlpatterns=[
	path('',HomeForumsView.as_view(),name='home'),
	path('fr-<int:id_forum>/<str:name_forum>/',ForumView.as_view(mode='forum'),name='forumview'),
	path('sfr-<int:id_forum>/<str:name_forum>/',ForumView.as_view(mode='subforum'),name='subforumview'),
	path('newthread/',NewPostView.as_view(),name='newthread'),
	path('update/<slug:slug_thread>/thread',NewPostView.as_view(mode='update'),name='updatethread'),
]

templates/snippets/container_card_forum.html
{% for forum in forums %}
<div class="detail-forum col-sm-6 pt-2 shadow">
	<a href="{% url "forum:forumview" id_forum=forum.id name_forum=forum.name %}" class="remove-link-format"> 
	<div class="forum-info">
		<img src="/media/logo_image/logocoba.jpg" class="img-fluid forum-logo">
		<div class="forum-posts d-flex flex-column justify-content-center">
			<p>{{forum.posts.all.count}} Post{{forum.posts.all.count|pluralize}}</p>
			<p>{{forum.subforums.all.count}} SubForum{{forum.subforum.all.count|pluralize}}</p>
		</div>
	</div>
	</a>
	<p><a href="{% url "forum:forumview" forum.id forum.name %}">{{forum.name|capfirst}}</a></p>
	<a href="{% url "forum:forumview" forum.id forum.name %}" class="btn btn-outline-orange d-block mb-2">See All Post and All SubForums</a>
</div>
{% endfor %}

templates/snippets/container_card_threads.html
{% for thread in threads %}
	<div class="post-container">
        {% if user.is_authenticated and user == thread.author %}
        <div class="container">
          <div class="row">
            <div class="post-edit ml-auto">
              <a href="{% url "forum:updatethread" thread.post_slug %}" class="edit-tread d-block-inline mr-1" data-action='edit'>Edit</a>
              <a href="javascript:void(0)" class="delete-thread d-block-inline mr-3" data-id='{{thread.post_slug}}' data-action='delete'>Hapus</a>
            </div>
          </div>
        </div>
        {% endif %}
        <div class="post-detail shadow">
         	<img src="{{thread.author.profile.user_photo.url}}" alt="user" class="profile-photo" />
          <div class="user-info">
            <h5><a href="{% url "creator" thread.author.username %}" class="profile-link">{{thread.author}}</a> <i class="fa fa-caret-right"></i> <a href="{% url "forum:forumview" thread.content_forum_post.id thread.content_forum_post.name%}" class="name-forum">{{thread.content_forum_post.name}}</a></h5>
            <p class="text-muted">{{thread.created}}</p>
          </div>
          <div class="hr-custom clearfix"></div>
          <div class="post-text pl-md-2 pl-lg-4">
          	<a href="{% url "thread" thread.post_slug thread.post_title %}" class="remove-link-format">
          		<p class="thread-title mb-2">{{thread.post_title}}</p>
              {{thread.body|truncatewords_html:33|safe}}
              <p class="clearfix"></p>
              <div class="reaction">
                   <span class="d-block-inline"><i class="fa fa-eye"></i> {{thread.post_views.all.count}}</span>
                  <span class="d-block-inline"><i class="ba-claps"></i> {{thread.upvotes}}</span>
                  <span class="d-block-inline"><i class="ba-punch"></i> {{thread.downvotes}}</span>
                  <span class="d-block-inline"><i class="fa fa-comment"></i> {{thread.post_comments.all.count}}</span>
            	 </div>
        	</a>
          </div>
        </div>
    </div>
    {%empty%}
		<h4 class="text-warning text-center p-4">Tidak Ada Thread</h4>
{% endfor %}

templates/snippets/css.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/bootstrap-select.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "batasibuk_icon/css/bata.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">

templates/snippets/delete_thread.html
<script type="text/javascript">
  $(document).on('click','.post-container',function(e){
    if(e.target.dataset.action=='delete'){
      e.preventDefault()
      let box_confirm=confirm('Anda Yakin Ingin Mengapus Thread Ini')
      if(box_confirm==true){
       let node_thread=$(this)
       let post_slug=e.target.dataset.id
       $.ajax({
        type:'POST',
        url:'api/posts/'+post_slug+'/delete',
        data:{
          csrfmiddlewaretoken:'{{csrf_token}}'
        },
        data_type:'json',
        success:function(data){
          if(data.delete==1){
            node_thread.fadeOut().remove()
            $('#sum-posts').text(data['count-posts'])
          }else{
            alert('Permission Denied')
          }
        }
       })
      }

    }else{
      console.log('alen')
      e.stopPropagation()
    }
    
  });
</script>

templates/snippets/follow.html
<script type="text/javascript">
		function follow_this(e){
			data_id=e.attr('data-id')
			follow_for=e.attr('data-action')
			$.ajax({
				type:'POST',
				url:'/api/follow/'+data_id+'/'+follow_for,
				data:{
					csrfmiddlewaretoken:'{{csrf_token}}',
				},
				data_type:'json',
				success:function(data){
					if(data.redirect_login){
						window.location.replace('/login?next=/api/follow/'+data_id+'/'+follow_for+'?next='+window.location.href)
					}
					e.toggleClass('active')
					if(data.follow_state_action){
						e.html(data.follow_state_action)
					}
					if($('#count-followers')[0]){
						$('#count-followers').text(data.sum_follow)
					}
				}
			})
		};

		$('.follow-this').click(function(e){
			e.preventDefault()
			follow_this($(this))
		});
</script>

templates/snippets/footer.html
<footer id="footer" class="shadow">
          <div class="footer-content">
              <h6>About</h6>
              <ul class="footer-links">
                <li><a href="">About us</a></li>
                <li><a href="">Contact us</a></li>
                 <li><a href="">Ask Batasibuk</a></li>
                <li><a href="">Terms</a></li>
                <li><a href="">FAQ</a></li>
              </ul>
          </div>
		  <div class="copyright">
			<p>Batasibuk <i class="fa fa-copyright"></i> {% now "Y" %}. All rights reserved</p>
		  </div>
		</footer>

templates/snippets/forum_recommend.html
{% load vote_follow_filter %}
<div class="suggest-forum-card">
  <h6 class="grey">Forum Recomendations</h6>
  {% for forum in forums  %}
  	<div class="follow-forum">
      <p><a href="{% url "forum:forumview" forum.id forum.name %}"class='remove-link-format'>{{forum.name}}</a></p>
      <a href="javascript:void(0)" class="btn btn-follow follow-this {%is_user_follow forum request %} " data-id='{{forum.id}}' data-action='forum'>{%is_user_follow forum request 'get_text'%}</a>
  </div>
  {% endfor %}
  
</div>

templates/snippets/js.html
{% load static %}


<script type="text/javascript" src="{% static "vendor/popper/popper.min.js" %}"></script>
<script type="text/javascript" src="{% static "vendor/bootstrap/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "vendor/bootstrap/bootstrap-select.min.js" %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$('[data-toggle=navtooltip]').tooltip();
	});
</script>
<script type="text/javascript" src="{% static "js/base.js" %}"></script>

templates/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light menu fixed-top">
  <div class="container-fluid">
    
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> 
  <a class="navbar-brand d-none d-md-block" href="{% url 'home' %}"><img src="{% static "image/logo.png" %}"></a>
  <a class="navbar-brand d-block d-md-none" href="{% url 'home' %}"><img style='height:30px!important;width:auto'src="{% static "image/justlogo.png" %}"></a>
  

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item home" >
        <a class="nav-link" href="{% url "home" %}" class="text-center" ><i class="fa fa-home"></i></a>
      </li>
      {% if user.is_authenticated %}
         <li class="nav-item dropdown">
           <a href="javascript:void(0)" class="nav-link dropdown-toggle btn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <div class="btn-profile align-middle">
               <img src="{{user.profile.user_photo.url}}" class="img-fluid">
            </div>
            <i class="fa fa-chevron-down"></i>
           </a>
           <ul class="dropdown-menu">
                    <li><a class="nav-link"  href="{% url "chat"%}">Room Chat</a></li>
                    <li><a class="nav-link"  href="{% url "profile" user %}">Account &amp; Settings</a></li>
                    <li><a class="nav-link" href="{% url "logout" %}">Keluar</a>
                    </li>
           </ul>
        </li>
        <li class="nav-item mt-sm-0 mt-2" >
         <a class="nav-link btn btn-thread" href="{% url "forum:newthread" %}"><i class="fa fa-plus"></i>&nbsp;Thread</a>
        </li>
      {% else %}
      <li class="nav-item register"  >
        <a class="nav-link" href="{% url "register" %}">Daftar</a>
      </li>
      <li class="nav-item login" >
        <a class="nav-link" href="{% url "login" %}">Masuk</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0 ml-2 " action='/search/' method="GET">
      <i data-role='submit' class="fa fa-search my-auto" style="cursor:pointer" onClick=$(this).parent().submit()></i>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='s'>
    </form>
  </div>
 </div>
</nav>

templates/snippets/online_creator.html
<style type="text/css">
  #online-kreator{
  margin: 0 0 40px 0;
  text-align: center;
  padding: 10px 0;
  border-radius: 4px;
  background-color: #fff;
}

#online-kreator .title{
  background: #fc8207;
  padding: 5px 20px;
  width: 70%;
  min-height: 30px;
  border-radius: 15px;
  position: relative;
  margin: 0 auto 20px;
  color: #fff;
  font-size: 14px;
  font-weight: 600;
}

ul.list-kreator{
  padding-left: 20px;
  padding-right: 20px;
  text-align: center;
  margin: 0;
}

ul.list-kreator li{
  list-style: none;
  position: relative;
  margin: 6px auto !important;
  padding-left: 3px;
  padding-right: 3px;
  display: inline-block;
}

ul.list-kreator li:after{
content: '';
  background: linear-gradient(90deg,#fc8207 0%,#f05c27 50%,#e7413f 100%);
  border: none;
  height: 12px;
  width: 12px;
  border-radius: 50%;
  position: absolute;
  bottom: -6px;
  border: 1px solid #fff;
  left: 0;
  right: 0;
  margin: auto;
}
</style>


<div id="online-kreator" class="shadow">
              <div class="title">Online Kreator</div>
              <ul class="list-kreator">
                <li><a href="newsfeed-messages.html" title="Linda Lohan"><img src="/media/profil_image/users/user-2.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="Sophia Lee"><img src="/media/profil_image/users/user-3.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="John Doe"><img src="/media/profil_image/users/user-4.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="Alexis Clark"><img src="/media/profil_image/users/user-5.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="James Carter"><img src="/media/profil_image/users/user-6.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="Robert Cook"><img src="/media/profil_image/users/user-7.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="Richard Bell"><img src="/media/profil_image/users/user-8.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="Anna Young"><img src="/media/profil_image/users/user-9.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
                <li><a href="newsfeed-messages.html" title="Julia Cox"><img src="/media/profil_image/users/user-10.jpg" alt="user" class="img-responsive profile-photo" /></a></li>
              </ul>
            </div><!--online kreator ends-->

templates/snippets/post_create.html
<div class="create-post shadow ">
            	
	<p class="d-flex"> 
		<img src="{{user.profile.user_photo.url}}" class="profile-photo">
		<span>Bagikan atau Tanya Sesuatu ke Batasibuk <a href="{% url 'forum:newthread' %}" class="btn btn-create-thread">Buat Thread</a></span>
	
	</p>
	<a href="{% url "forum:home" %}" class="btn btn-forum ml-auto">See Batasibuk Forum</a>
</div>

templates/snippets/post_recommends.html
{% load text_custom %}
<div class="trend-threads-card shadow">
  <h6>Top Recommend</h6>
  {% for thread  in posts %}
  	<div class="trend-thread">
      <a href="{% url 'thread' thread.post_slug thread.post_title %}" class="remove-link-format">
      	<p class="threads-title">{{thread.post_title}}</p >
      	<p class="thread-detail"><span class='text-muted'>Published {{thread.created|to_time_since}}</span><span class="thread-r">{{thread.post_recommends.all.count}}<i class="ba-recomend"></i></span></p>
      </a>
  	</div>
  {% endfor %}
</div>

templates/snippets/profile_card.html
<div class="profile-card shadow ">
    <a href="{% url 'profile' user.username %}" class="profile-name">{{user.username}}</a>
    <p class="profile-info">{{user.profile.info}}</p>
    <div class="profile-fields">
        <img src="{{user.profile.user_photo.url}}" class="profile-photo img-fluid" />
        <div class="profile-stats d-flex flex-row justify-content-around">
            <a href="" class="d-block">
                <span class="d-block">Post</span>
                <span id='sum-posts'>{{user.posts.all.count}}</span>
            </a>
            <a href="" class="d-block">
                <span class="d-block">Pengikut</span>
                <span>{{user.profile.followers.all.count}}</span>
            </a>
        </div>
    </div>
</div>

templates/snippets/this_paginated.html
{% if is_paginated %}
<div class="posts-page px-4 mb-3">
	{% if page_obj.has_previous %}
		<a href="?page=1" class="btn btn-outline-orange mt-4">First</a>
		<a href="?page={{page_obj.previous_page_number}}" class="btn btn-outline-orange mt-4"><i class="fa fa-arrow-left"></i></a>
	{% endif %}
	{% for num in page_obj.paginator.page_range  %}
		{% if page_obj.number == num %}
			<a href="?page={{num}}" class="btn btn-orange mt-4">{{num}}</a>
		{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
			<a href="?page={{num}}" class="btn btn-outline-orange mt-4">{{num}}</a>
		{% endif %}
	{% endfor %}
	{% if page_obj.has_next %}
		<a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-orange mt-4"><i class="fa fa-arrow-right"></i></a>
		<a href="?page={{page_obj.paginator.num_pages}}" class="btn btn-outline-orange mt-4">Last</a>
	{% endif %}
	</div>
{% endif %}